#!/bin/sh

# Check for the correct number of arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <test target> <project path>"
    exit 1
fi

test_target="$1"
project_path="$2"

cd $project_path/code/test
make clean
make distclean
make $test_target
../build.linux/nachos -e $test_target