#!/bin/sh

project_path="/home/os2023/os23team41/NachOS-4.0_MP1"

# Build Nachos
bash "$project_path/script/build_nachos" "$project_path"

run_test() {
    local test_name="$1"
    echo "***************************************"
    
    if [ "$test_name" = "fileIO_test1" ]; then
        rm -f "$project_path/code/test/file1.test"
    fi

    bash "$project_path/script/build_and_run_test" "$test_name $project_path"
    cat "$project_path/code/test/file1.test"
    echo ""
    echo "***************************************"
}

# Run tests
run_test "fileIO_test1"
run_test "fileIO_test2"